FROM golang:1.26-trixie AS builder

RUN apt-get update && apt-get upgrade -y && \
    mkdir -p /var/lib/sqlite

WORKDIR /go/src/github.com/ory/kratos

COPY go.mod go.sum ./
COPY oryx/go.mod oryx/go.sum oryx/
COPY pkg/client-go/go.* pkg/client-go/

ENV CGO_ENABLED=1
ENV CGO_CPPFLAGS=-DSQLITE_DEFAULT_FILE_PERMISSIONS=0600

RUN go mod download
COPY . .

ARG VERSION
ARG COMMIT
ARG BUILD_DATE

RUN --mount=type=cache,target=/root/.cache/go-build go build \
    -ldflags="-X 'github.com/ory/kratos/driver/config.Version=${VERSION}' \
              -X 'github.com/ory/kratos/driver/config.Date=${BUILD_DATE}' \
              -X 'github.com/ory/kratos/driver/config.Commit=${COMMIT}'" \
    -o /usr/bin/kratos

FROM alpine:3.20.0

RUN addgroup -S ory; \
    adduser -S ory -G ory -D -u 10000 -h /home/ory -s /bin/nologin; \
    chown -R ory:ory /home/ory
RUN apk --update upgrade && apk --no-cache add ca-certificates

WORKDIR /home/ory
COPY --from=builder --chown=ory:ory /usr/bin/kratos /usr/bin/kratos

RUN mkdir -p /var/lib/sqlite && chown ory:ory /var/lib/sqlite
VOLUME /var/lib/sqlite
VOLUME /home/ory

EXPOSE 4433 4434
USER 10000
ENTRYPOINT ["kratos"]
CMD ["serve"]
